### ISSUE TITLE
NameError in main.py

### ISSUE THREAD

**Issue by mohammadmostafarostamkhani** [fuxianghuang1/LGLI#1]
I encountered a NameError when trying to run main.py. The error suggests that the name 'img_text_composition_models_re' is not defined.

Error Traceback
```
Traceback (most recent call last):
  File "/content/LGLI/main.py", line 484, in <module>
    main()
  File "/content/LGLI/main.py", line 458, in main
    model, optimizer = create_model_and_optimizer(opt, [t for t in trainset.get_all_texts()])
  File "/content/LGLI/main.py", line 176, in create_model_and_optimizer
    img_text_composition_models =  img_text_composition_models_re 
NameError: name 'img_text_composition_models_re' is not defined. Did you mean: 'img_text_composition_models'?
```

**Comment by fuxianghuang1** [comment]
Thank you for reaching out and showing interest in our paper and the related code on GitHub.   I'm sorry to hear that you've encountered an issue while running the main.py script.
Regarding the "img_text_composition_models_re" variable that's causing the NameError, it's possible that this was some part of the code that was perhaps in a previous version or was accidentally left in a way that's now causing confusion.
One approach you could take is indeed to try commenting out the line of code where this variable is being used.
